---
- hosts: all
  sudo: true

  vars:
      username: elspeth
      sitename: superlists-andrew
      site_repo: https://github.com/MrLokans/TDD_Python
      django_port: 8000
  
  pre_tasks:
    - name: update apt cache
      apt: update_cache=yes

  tasks:
    - name: add user elspeth
      user: name={{ username }} shell=/bin/bash groups=sudo

    - name: install git, python and pip
      apt: name={{ item }} state=present
      with_items:
        - nginx
        - git
        - python3
        - python3-pip
        - nodejs
        - npm

    - name: make nodejs available by 'node' alias
      file: src=/usr/bin/nodejs dest=/usr/bin/node state=link
    # may be its not really a correct way, rethink later 
    - name: install bower to get JS deps
      npm: name=bower global=yes

    - name: install virtualenv
      pip: name=virtualenv state=present executable=pip3

      # Rethink user usage later
    - name: create folders

      file: path=~/sites/{{ sitename }}/static state=directory recurse=yes
      file: path=~/sites/{{ sitename }}/virtualenv state=directory recurse=yes
      file: path=~/sites/{{ sitename }}/source state=directory recurse=yes

      ignore_errors: yes

      become: yes
      become_user: "{{ username }}"


    - name: create venv and install django in it
      pip: virtualenv=~/sites/{{ sitename }}/virtualenv name={{ item }}
      with_items:
            - django
            - gunicorn
      become: yes
      become_user: "{{ username }}"

    # now vagrant settings are stored in repo, which is not a nice way
    # perhaps its better to store project sources in 'master' branch only
    # or to checkout only specific folder (how?)
    # see 'sparse checkout' http://bit.ly/1jqTlMH
    - name: checkout source repository
      git: repo={{ site_repo }} dest=~/sites/{{ sitename }}/source
      become: yes
      become_user: "{{ username }}"

    - name: copy nginx config
      template: src=templates/nginx.conf.j2
                dest=/etc/nginx/sites-available/{{ sitename }}

    - name: enable nginx sitename
      file: src=/etc/nginx/sites-available/{{ sitename }}
            dest=/etc/nginx/sites-enabled/{{ sitename }}
            state=link

    - name: remove default nginx config
      file: path=/etc/nginx/sites-enabled/default
            state=absent

    - name: reload nginx
      service: name=nginx state=reloaded


    - file: path=~/sites/{{ sitename }}/source/database state=directory recurse=yes
      become: yes
      become_user: "{{ username }}"
      ignore_errors: yes

    - name: prepare databases
      django_manage:  >
                virtualenv=/home/{{ username }}/sites/{{ sitename }}/virtualenv
                app_path=/home/{{ username }}/sites/{{ sitename }}/source/superlists
                command=migrate
      become: yes
      become_user: "{{ username }}"      
       
    # that does not seem to be the right way to manage statics
    - name : install static dependencies
      command: bower install
      args:
        chdir: ~/sites/{{ sitename }}/source/superlists/lists/static
      become: yes
      become_user: "{{ username }}"

    - name: collect statics
      django_manage:  >
                virtualenv=/home/{{ username }}/sites/{{ sitename }}/virtualenv
                app_path=/home/{{ username }}/sites/{{ sitename }}/source/superlists
                command='collectstatic --noinput'
      become: yes
      become_user: "{{ username }}"

    # a crappy way to run app
    # next thing is ti write upstart/systemd units which handle start
    - command: bash -c 'nohup ~/sites/{{ sitename }}/virtualenv/bin/gunicorn superlists.wsgi:application --bind 127.0.0.1:{{ django_port }} &'
      args:
        chdir: ~/sites/{{ sitename }}/source/superlists
      # async: 45
      # poll: 0
      become: yes
      become_user: "{{ username }}"
