---
- hosts: all
  sudo: true

  vars:
      username: elspeth
      sitename: superlists-andrew
      site_repo: https://github.com/MrLokans/TDD_Python
  pre_tasks:
    - name: update apt cache
      apt: update_cache=yes

  tasks:
    - name: install nginx
      apt: name=nginx state=present

    - name: add user elspeth
      user: name={{ username }} shell=/bin/bash groups=sudo

    - name: install git, python and pip
      apt: name=git state=present
      apt: name=python3 state=present
      apt: name=python3-pip

    - name: install virtualenv
      pip: name=virtualenv state=present executable=pip3

      # Rethink user usage later
    - name: create folders
      file: path=~/sites/{{ sitename }}/database state=directory recurse=yes
      file: path=~/sites/{{ sitename }}/static state=directory recurse=yes
      file: path=~/sites/{{ sitename }}/virtualenv state=directory recurse=yes
      file: path=~/sites/{{ sitename }}/source state=directory recurse=yes

    - name: checkout source repository
      git: repo={{ site_repo }} dest=~/sites/{{ sitename }}/source

    - name: create venv and install django in it
      pip: virtualenv=~/sites/{{ sitename }}/virtualenv name=django version=1.7

    - name: copy nginx config
      template: src=templates/nginx.conf.j2
                dest=/etc/nginx/sites-available/{{ sitename }}
    - name: enable nginx sitename
      file: src=/etc/nginx/sites-available/{{ sitename }}
            dest=/etc/nginx/sites-enabled/{{ sitename }}
            state=link

    - name: remove default nginx config
      file: path=/etc/nginx/sites-enabled/default
            state=absent

    - name: reload nginx
      service: name=nginx state=reloaded

    # manage.py can not be found! needs to be fixed!
    - name: prepare databases
      django_manage: app_path=~/sites/{{ sitename }}/source/superlists/
                     command='migrate --noinput'
                     virtualenv=~/sites/{{ sitename }}/virtualenv

    - name: run application
      django_manage: >
                app_path=~/sites/{{ sitename }}/source/superlists/
                command=runserver
                virtualenv=~/sites/{{ sitename }}/virtualenv

