# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  # config.vm.network "forwarded_port", guest: 80, host: 80
  config.vm.network "private_network", ip: "172.28.128.101"  
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
